In [88]:
import pandas as pd
import json

In [89]:
fifa = pd.read_csv("fifalarge.csv", low_memory=False)
fifa.head()

,name,age,overall,nationality,club,bestposition,playerphoto,flagphoto,potential,height,...,wage,totalstats,basestats,attacking,skill,movement,power,mentality,defending,goalkeeping
0,G. Pasquale,33,69,Italy,Udinese,LWB,https://cdn.sofifa.com/players/000/002/16_120.png,https://cdn.sofifa.com/flags/it.png,69,"6'0""",...,7000.0,1929,408,71,71,74,78,76,76,12
1,Luis García,37,71,Spain,KAS Eupen,CM,https://cdn.sofifa.com/players/000/016/19_120.png,https://cdn.sofifa.com/flags/es.png,71,"5'10""",...,7000.0,1906,385,77,78,65,73,86,56,12
2,J. Cole,33,71,England,Coventry City,CAM,https://cdn.sofifa.com/players/000/027/16_120.png,https://cdn.sofifa.com/flags/gb-eng.png,71,"5'9""",...,15000.0,1770,354,77,82,63,64,75,36,11
3,D. Yorke,36,68,Trinidad &amp; Tobago,Sunderland,ST,https://cdn.sofifa.com/players/000/036/09_120.png,https://cdn.sofifa.com/flags/tt.png,82,"5'11""",...,0.0,1348,369,60,54,37,53,64,27,15
4,Iniesta,36,81,Spain,Vissel Kobe,CAM,https://cdn.sofifa.com/players/000/041/20_120.png,https://cdn.sofifa.com/flags/es.png,81,"5'7""",...,12000.0,2014,420,84,86,74,66,87,66,10

In [90]:
fifa.shape

(17125, 25)

In [91]:
#count total purchases for future calculations
total = fifa["nationality"].count()

#find unique purchasers
unique_country = fifa["nationality"].unique()

#calculate total numbers of players
num_countries=len(unique_country)
num_players=total

print("Total Countries = ",num_countries)
print("Total Players = ",num_players)

Total Countries =  167
Total Players =  17125

In [92]:

# Use GroupBy to separate the data into fields according to "Gender" values
grouped_df = fifa.groupby(['nationality'])


#count purchasers
player_count = grouped_df["nationality"].count()

#calculate total price
avg_overall = grouped_df["overall"].mean()

#calculate average price
#g_avg = g_price / grouped_df["SN"].count()

#calcualte total purchase per person
#g_pur = g_price / unique_users["Gender"].value_counts()

#set dictionary for proper formatting
#format_dict = {'Player Count':'{:.0f}', 'Average Overall': '${:,.0f}'}

#create dataframe for output
fifa_countries = pd.DataFrame({"Player Count":player_count,
                                "Average Overall": avg_overall})

#output df in proper format
#fifa_countries.style.format(format_dict)
high_count=fifa_countries["Player Count"].max()

fifa_countries["Weighted Count"]=(fifa_countries["Player Count"]/high_count)*100



fifa_countries

             Player Count  Average Overall  Weighted Count
nationality
Afghanistan             3        61.333333        0.175747
Albania                42        66.809524        2.460457
Algeria                51        71.549020        2.987698
Andorra                 1        63.000000        0.058582
Angola                 19        68.526316        1.113064
...                   ...              ...             ...
Venezuela             140        64.678571        8.201523
Vietnam                 2        63.500000        0.117165
Wales                 133        63.736842        7.791447
Zambia                 10        67.300000        0.585823
Zimbabwe               14        68.642857        0.820152

[167 rows x 3 columns]

In [93]:
#{ country: "Brazil", color: "#009900", score: "95" },
#  { country: "Argentina", color: "#7ade45", score: "85" },
#  { country: "Colombia", color: "#a3e84f", score: "75" },
#  { country: "Uruguay", color: "#d9f000", score: "65" },
#  { country: "Paraguay", color: "#ffff00", score: "55" },
#  { country: "Chile", color: "#fcf200", score: "45" },
#  { country: "Peru", color: "#ffcc52", score: "35" },
#  { country: "Venezuela", color: "#ff993d", score: "25" },
#  { country: "Ecuador", color: "#ff8033", score: "15" },
#  { country: "Bolivia", color: "#cc0000", score: "5" }];





#color_name
colors = ["#009900","#7ade45","#a3e84f","#d9f000","#ffff00","#fcf200","#ffcc52","#ff993d","#ff8033","#cc0000"]


# set series empty to append
color_list =[]

#  count the unique mice per drug regimen
for i in fifa_countries["Weighted Count"]:
    if i >= 90:
        color_list.append(colors[0])
    elif i >= 80:
        color_list.append(colors[1])
    elif i >= 70:
        color_list.append(colors[2])
    elif i >= 60:
        color_list.append(colors[3])
    elif i >= 50:
        color_list.append(colors[4])
    elif i >= 40:
        color_list.append(colors[5])
    elif i >= 30:
        color_list.append(colors[6])
    elif i >= 20:
        color_list.append(colors[7])
    elif i >= 10:
        color_list.append(colors[8])
    else:
        color_list.append(colors[9])   
    
    
# create a datafram of unique mice per drug without duplicates for graphing
#drug_mice = pd.DataFrame({"Drug Regimen":unique_mice.index,
 #                               "Number of Mice": mice_pd})

# create a datafram of unique mice per drug without duplicates for graphing
#drug_mice = pd.DataFrame({"Drug Regimen":unique_mice.index,
 #                               "Number of Mice": mice["Mouse ID"].count()})

fifa_countries["Color"]=color_list



# sort Top spenders from highest to lowest purchase value
fifa_countries = fifa_countries.sort_values("Player Count", ascending=False)

fifa_countries



fifa_countries



#fifa_countries["Weighted Count"]=(fifa_countries["Player Count"]/high_count)*100

               Player Count  Average Overall  Weighted Count    Color
nationality
England                1707        63.642648      100.000000  #009900
Germany                1154        66.205373       67.603984  #d9f000
Spain                  1121        69.619982       65.670767  #d9f000
France                  990        67.792929       57.996485  #ffff00
Brazil                  857        72.004667       50.205038  #ffff00
...                     ...              ...             ...      ...
New Caledonia             1        71.000000        0.058582  #cc0000
Nicaragua                 1        56.000000        0.058582  #cc0000
Indonesia                 1        56.000000        0.058582  #cc0000
Saint Lucia               1        64.000000        0.058582  #cc0000
Palestine                 1        61.000000        0.058582  #cc0000

[167 rows x 4 columns]

In [94]:
del fifa_countries["Average Overall"]
del fifa_countries["Weighted Count"]



fifa_countries

               Player Count    Color
nationality
England                1707  #009900
Germany                1154  #d9f000
Spain                  1121  #d9f000
France                  990  #ffff00
Brazil                  857  #ffff00
...                     ...      ...
New Caledonia             1  #cc0000
Nicaragua                 1  #cc0000
Indonesia                 1  #cc0000
Saint Lucia               1  #cc0000
Palestine                 1  #cc0000

[167 rows x 2 columns]

In [96]:
fifa_countries.reset_index(level=0, inplace=True)

In [97]:
fifa_countries

       nationality  Player Count    Color
0          England          1707  #009900
1          Germany          1154  #d9f000
2            Spain          1121  #d9f000
3           France           990  #ffff00
4           Brazil           857  #ffff00
..             ...           ...      ...
162  New Caledonia             1  #cc0000
163      Nicaragua             1  #cc0000
164      Indonesia             1  #cc0000
165    Saint Lucia             1  #cc0000
166      Palestine             1  #cc0000

[167 rows x 3 columns]

In [100]:
print(fifa_countries.to_json(orient="records"))

[{"nationality":"England","Player Count":1707,"Color":"#009900"},{"nationality":"Germany","Player Count":1154,"Color":"#d9f000"},{"nationality":"Spain","Player Count":1121,"Color":"#d9f000"},{"nationality":"France","Player Count":990,"Color":"#ffff00"},{"nationality":"Brazil","Player Count":857,"Color":"#ffff00"},{"nationality":"Argentina","Player Count":778,"Color":"#fcf200"},{"nationality":"Italy","Player Count":565,"Color":"#ffcc52"},{"nationality":"Netherlands","Player Count":475,"Color":"#ff993d"},{"nationality":"Portugal","Player Count":365,"Color":"#ff993d"},{"nationality":"United States","Player Count":358,"Color":"#ff993d"},{"nationality":"Mexico","Player Count":345,"Color":"#ff993d"},{"nationality":"Uruguay","Player Count":335,"Color":"#ff8033"},{"nationality":"Colombia","Player Count":305,"Color":"#ff8033"},{"nationality":"Japan","Player Count":295,"Color":"#ff8033"},{"nationality":"Poland","Player Count":291,"Color":"#ff8033"},{"nationality":"Scotland","Player Count":281,"Color":"#ff8033"},{"nationality":"Republic of Ireland","Player Count":278,"Color":"#ff8033"},{"nationality":"Belgium","Player Count":263,"Color":"#ff8033"},{"nationality":"Sweden","Player Count":260,"Color":"#ff8033"},{"nationality":"Norway","Player Count":260,"Color":"#ff8033"},{"nationality":"Denmark","Player Count":258,"Color":"#ff8033"},{"nationality":"Austria","Player Count":245,"Color":"#ff8033"},{"nationality":"Turkey","Player Count":226,"Color":"#ff8033"},{"nationality":"Switzerland","Player Count":211,"Color":"#ff8033"},{"nationality":"Paraguay","Player Count":180,"Color":"#ff8033"},{"nationality":"Chile","Player Count":180,"Color":"#ff8033"},{"nationality":"Romania","Player Count":166,"Color":"#cc0000"},{"nationality":"Korea Republic","Player Count":155,"Color":"#cc0000"},{"nationality":"Australia","Player Count":149,"Color":"#cc0000"},{"nationality":"Nigeria","Player Count":141,"Color":"#cc0000"},{"nationality":"Croatia","Player Count":141,"Color":"#cc0000"},{"nationality":"Senegal","Player Count":141,"Color":"#cc0000"},{"nationality":"Venezuela","Player Count":140,"Color":"#cc0000"},{"nationality":"Peru","Player Count":138,"Color":"#cc0000"},{"nationality":"Ecuador","Player Count":137,"Color":"#cc0000"},{"nationality":"Ghana","Player Count":135,"Color":"#cc0000"},{"nationality":"Wales","Player Count":133,"Color":"#cc0000"},{"nationality":"China PR","Player Count":131,"Color":"#cc0000"},{"nationality":"Serbia","Player Count":131,"Color":"#cc0000"},{"nationality":"Czech Republic","Player Count":124,"Color":"#cc0000"},{"nationality":"Ivory Coast","Player Count":119,"Color":"#cc0000"},{"nationality":"Russia","Player Count":114,"Color":"#cc0000"},{"nationality":"Saudi Arabia","Player Count":103,"Color":"#cc0000"},{"nationality":"Greece","Player Count":96,"Color":"#cc0000"},{"nationality":"Cameroon","Player Count":96,"Color":"#cc0000"},{"nationality":"Canada","Player Count":96,"Color":"#cc0000"},{"nationality":"Morocco","Player Count":91,"Color":"#cc0000"},{"nationality":"Northern Ireland","Player Count":81,"Color":"#cc0000"},{"nationality":"Ukraine","Player Count":72,"Color":"#cc0000"},{"nationality":"Mali","Player Count":70,"Color":"#cc0000"},{"nationality":"DR Congo","Player Count":69,"Color":"#cc0000"},{"nationality":"Bosnia Herzegovina","Player Count":68,"Color":"#cc0000"},{"nationality":"Finland","Player Count":61,"Color":"#cc0000"},{"nationality":"Bolivia","Player Count":59,"Color":"#cc0000"},{"nationality":"Slovakia","Player Count":58,"Color":"#cc0000"},{"nationality":"South Africa","Player Count":57,"Color":"#cc0000"},{"nationality":"Slovenia","Player Count":53,"Color":"#cc0000"},{"nationality":"Iceland","Player Count":52,"Color":"#cc0000"},{"nationality":"Algeria","Player Count":51,"Color":"#cc0000"},{"nationality":"Kosovo","Player Count":50,"Color":"#cc0000"},{"nationality":"Bulgaria","Player Count":46,"Color":"#cc0000"},{"nationality":"Hungary","Player Count":43,"Color":"#cc0000"},{"nationality":"Albania","Player Count":42,"Color":"#cc0000"},{"nationality":"New Zealand","Player Count":37,"Color":"#cc0000"},{"nationality":"India","Player Count":36,"Color":"#cc0000"},{"nationality":"Egypt","Player Count":35,"Color":"#cc0000"},{"nationality":"Jamaica","Player Count":34,"Color":"#cc0000"},{"nationality":"Tunisia","Player Count":32,"Color":"#cc0000"},{"nationality":"Guinea","Player Count":32,"Color":"#cc0000"},{"nationality":"Costa Rica","Player Count":32,"Color":"#cc0000"},{"nationality":"Israel","Player Count":29,"Color":"#cc0000"},{"nationality":"Gambia","Player Count":25,"Color":"#cc0000"},{"nationality":"Montenegro","Player Count":25,"Color":"#cc0000"},{"nationality":"Georgia","Player Count":25,"Color":"#cc0000"},{"nationality":"Burkina Faso","Player Count":24,"Color":"#cc0000"},{"nationality":"Cape Verde","Player Count":24,"Color":"#cc0000"},{"nationality":"North Macedonia","Player Count":22,"Color":"#cc0000"},{"nationality":"Honduras","Player Count":21,"Color":"#cc0000"},{"nationality":"Guinea Bissau","Player Count":20,"Color":"#cc0000"},{"nationality":"Iran","Player Count":20,"Color":"#cc0000"},{"nationality":"Angola","Player Count":19,"Color":"#cc0000"},{"nationality":"Gabon","Player Count":19,"Color":"#cc0000"},{"nationality":"Congo","Player Count":19,"Color":"#cc0000"},{"nationality":"Curacao","Player Count":19,"Color":"#cc0000"},{"nationality":"United Arab Emirates","Player Count":17,"Color":"#cc0000"},{"nationality":"Togo","Player Count":16,"Color":"#cc0000"},{"nationality":"Zimbabwe","Player Count":14,"Color":"#cc0000"},{"nationality":"Panama","Player Count":11,"Color":"#cc0000"},{"nationality":"Kenya","Player Count":11,"Color":"#cc0000"},{"nationality":"Cyprus","Player Count":11,"Color":"#cc0000"},{"nationality":"Benin","Player Count":11,"Color":"#cc0000"},{"nationality":"Haiti","Player Count":10,"Color":"#cc0000"},{"nationality":"Zambia","Player Count":10,"Color":"#cc0000"},{"nationality":"Lithuania","Player Count":10,"Color":"#cc0000"},{"nationality":"Luxembourg","Player Count":10,"Color":"#cc0000"},{"nationality":"Comoros","Player Count":10,"Color":"#cc0000"},{"nationality":"Madagascar","Player Count":9,"Color":"#cc0000"},{"nationality":"Sierra Leone","Player Count":9,"Color":"#cc0000"},{"nationality":"Guyana","Player Count":9,"Color":"#cc0000"},{"nationality":"Latvia","Player Count":8,"Color":"#cc0000"},{"nationality":"Moldova","Player Count":8,"Color":"#cc0000"},{"nationality":"Mauritania","Player Count":8,"Color":"#cc0000"},{"nationality":"Uganda","Player Count":8,"Color":"#cc0000"},{"nationality":"Armenia","Player Count":8,"Color":"#cc0000"},{"nationality":"Uzbekistan","Player Count":7,"Color":"#cc0000"},{"nationality":"Antigua &amp; Barbuda","Player Count":7,"Color":"#cc0000"},{"nationality":"Equatorial Guinea","Player Count":7,"Color":"#cc0000"},{"nationality":"Trinidad &amp; Tobago","Player Count":6,"Color":"#cc0000"},{"nationality":"Kazakhstan","Player Count":6,"Color":"#cc0000"},{"nationality":"Thailand","Player Count":6,"Color":"#cc0000"},{"nationality":"Burundi","Player Count":6,"Color":"#cc0000"},{"nationality":"Dominican Republic","Player Count":6,"Color":"#cc0000"},{"nationality":"Belarus","Player Count":5,"Color":"#cc0000"},{"nationality":"Central African Republic","Player Count":5,"Color":"#cc0000"},{"nationality":"Cuba","Player Count":5,"Color":"#cc0000"},{"nationality":"Faroe Islands","Player Count":5,"Color":"#cc0000"},{"nationality":"Liberia","Player Count":5,"Color":"#cc0000"},{"nationality":"Liechtenstein","Player Count":5,"Color":"#cc0000"},{"nationality":"South Sudan","Player Count":4,"Color":"#cc0000"},{"nationality":"Iraq","Player Count":4,"Color":"#cc0000"},{"nationality":"Azerbaijan","Player Count":4,"Color":"#cc0000"},{"nationality":"Lebanon","Player Count":4,"Color":"#cc0000"},{"nationality":"Korea DPR","Player Count":4,"Color":"#cc0000"},{"nationality":"Estonia","Player Count":4,"Color":"#cc0000"},{"nationality":"Libya","Player Count":4,"Color":"#cc0000"},{"nationality":"Montserrat","Player Count":3,"Color":"#cc0000"},{"nationality":"Mozambique","Player Count":3,"Color":"#cc0000"},{"nationality":"Sudan","Player Count":3,"Color":"#cc0000"},{"nationality":"Chinese Taipei","Player Count":3,"Color":"#cc0000"},{"nationality":"Afghanistan","Player Count":3,"Color":"#cc0000"},{"nationality":"Philippines","Player Count":3,"Color":"#cc0000"},{"nationality":"Grenada","Player Count":3,"Color":"#cc0000"},{"nationality":"El Salvador","Player Count":3,"Color":"#cc0000"},{"nationality":"Syria","Player Count":2,"Color":"#cc0000"},{"nationality":"Malaysia","Player Count":2,"Color":"#cc0000"},{"nationality":"Belize","Player Count":2,"Color":"#cc0000"},{"nationality":"Namibia","Player Count":2,"Color":"#cc0000"},{"nationality":"Jordan","Player Count":2,"Color":"#cc0000"},{"nationality":"Chad","Player Count":2,"Color":"#cc0000"},{"nationality":"Vietnam","Player Count":2,"Color":"#cc0000"},{"nationality":"Niger","Player Count":2,"Color":"#cc0000"},{"nationality":"Hong Kong","Player Count":2,"Color":"#cc0000"},{"nationality":"Malawi","Player Count":1,"Color":"#cc0000"},{"nationality":"Puerto Rico","Player Count":1,"Color":"#cc0000"},{"nationality":"Macau","Player Count":1,"Color":"#cc0000"},{"nationality":"Aruba","Player Count":1,"Color":"#cc0000"},{"nationality":"Barbados","Player Count":1,"Color":"#cc0000"},{"nationality":"Gibraltar","Player Count":1,"Color":"#cc0000"},{"nationality":"Malta","Player Count":1,"Color":"#cc0000"},{"nationality":"Andorra","Player Count":1,"Color":"#cc0000"},{"nationality":"Papua New Guinea","Player Count":1,"Color":"#cc0000"},{"nationality":"Rwanda","Player Count":1,"Color":"#cc0000"},{"nationality":"Tanzania","Player Count":1,"Color":"#cc0000"},{"nationality":"S\u00e3o Tom\u00e9 &amp; Pr\u00edncipe","Player Count":1,"Color":"#cc0000"},{"nationality":"Saint Kitts and Nevis","Player Count":1,"Color":"#cc0000"},{"nationality":"Bermuda","Player Count":1,"Color":"#cc0000"},{"nationality":"Brunei Darussalam","Player Count":1,"Color":"#cc0000"},{"nationality":"Suriname","Player Count":1,"Color":"#cc0000"},{"nationality":"Qatar","Player Count":1,"Color":"#cc0000"},{"nationality":"Guam","Player Count":1,"Color":"#cc0000"},{"nationality":"Eritrea","Player Count":1,"Color":"#cc0000"},{"nationality":"Singapore","Player Count":1,"Color":"#cc0000"},{"nationality":"New Caledonia","Player Count":1,"Color":"#cc0000"},{"nationality":"Nicaragua","Player Count":1,"Color":"#cc0000"},{"nationality":"Indonesia","Player Count":1,"Color":"#cc0000"},{"nationality":"Saint Lucia","Player Count":1,"Color":"#cc0000"},{"nationality":"Palestine","Player Count":1,"Color":"#cc0000"}]

In [101]:
fifa_countries.to_json('test.json',orient="records")

In [ ]:
# Save a cleaned version of the file:

fifa_countries.to_csv("tempbig.csv", encoding="utf-8", index=True, header=True